plugins: [jekyll-paginate]

permalink: /:categories/:title/

highlighter: rouge
markdown: kramdown
kramdown:
  input:  GFM
  syntax_highlighter: rouge


paginate: 10
paginate_path: "page/:num"
baseurl: ""



defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
      styles : [highlight.css,gitment.css,post.css]
      scripts : [gitment.js, post.js]



title: "Jizy的Git博客"
email: david-jzy@outlook.com
description: ""
github:
  username: 15262331232
swiftype:
  searchId: iXZyPokVfxFaBTvi64Y6
gitment:
    repo: blog.github.io
    enable: true
    client_id: 3efaf9d13f44c16bbcfd
    client_secret: b11a543135681ed6f8cba78efeba53129842d198

url: "https://15262331232.github.io/blog.github.io"
imgrepo: "https://bit-ranger.github.io/blog/static/img"


#url: "http://127.0.0.1:4000"
#imgrepo: "http://127.0.0.1:4000/static/img"

